version: '3'

services:
  backend-service:
    image: rajveermalviya/grpc-browser:backend
    environment:
      FIREBASE_CREDENTIALS: '...YOUR...CREDENTIALS...JSON...CONTENT...'

  proxy-service:
    image: rajveermalviya/grpc-browser:proxy
    ports:
      - '8080:8080'
      - '10000:10000'

  frontend-service:
    image: rajveermalviya/grpc-browser:frontend
