version: '3'

services:
  backend:
    image: rajveermalviya/grpc-browser:backend

  proxy:
    image: rajveermalviya/grpc-browser:proxy
    ports:
      - 8080:8080
      - 9090:9090

  frontend:
    build: ./frontend
