version: '3'

services:
  backend-service:
    build: ./backend
    environment:
      FIREBASE_CREDENTIALS: '...YOUR...CREDENTIALS...JSON...CONTENT...'

  proxy-service:
    build: ./proxy
    ports:
      - '8080:8080'
      - '9090:9090'

  frontend-service:
    build: ./frontend
